---

- hosts: localhost
  sudo: yes
  vars:
    proxy_env:
      http_proxy: http://MYSUPERPROXY:8080
      https_proxy: http://MYSUPERPROXY:8080
  roles:
    - common

  environment: "{{ proxy_env }}"
  