---
  
- name: un tar
  unarchive: src=https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz dest=/usr/local copy=no

- name: set PATH
  lineinfile: dest=/etc/profile line="{{ item }}" 
  with_items:
    - "export GOROOT=/home/go"
    - "export PATH=PATH:/usr/local/go/bin:$GOROOT/bin"
