---
  
- name: un tar
  shell: wget -qO- https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz | tar xvz -C /usr/local 
  tags: install
  

- name: set PATH
  lineinfile: dest=/etc/profile line="{{ item }}" 
  with_items:
    - "export GOROOT=/usr/local/go"
    - "export GOPATH=/home/go"
    - "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin"
  tags: testing

