---

- name: clean previous go installation
  file: path={{ GOROOT }}/go state=absent 

- file: path={{ item }} state=directory mode=0755 owner={{ ansible_user }}
  with_items:
    - "/etc/env_custom"
    - "/home/go"

- file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ PROTOCPATH }}"

- name: Install go
  unarchive:
    src: https://storage.googleapis.com/golang/go{{ GOVERSION }}.linux-amd64.tar.gz
    dest: "{{ GOROOT }}"
    remote_src: yes
  tags: go

- name: Install protobuf
  unarchive:
    src: https://github.com/google/protobuf/releases/download/v{{ PROTOCVERSION }}/protoc-{{ PROTOCVERSION }}-linux-x86_64.zip
    dest: "{{ PROTOCPATH }}"
    mode: 0755
    remote_src: yes
  tags: testing

- name: create
  template: src=env_go.sh.j2 dest=/etc/env_custom/env_go.sh mode=0755

- name: set PATH
  lineinfile: dest=/etc/profile line="{{ item }}" 
  with_items:
    - "source /etc/env_custom/env_go.sh"
