---
- name: Docker prerequisities
  yum: name=yum-utils state=present

- name: Remove old docker version
  yum: name={{ item }} state=absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - container-selinux
    - docker-engine-selinux
    - docker-engine
    - docker-ce

- name: Add docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Active Edge
  shell: yum-config-manager --enable docker-ce-edge

- name: Install docker
  yum:
    name: docker-ce-{{ DOCKER_VERSION }}.ce-1.el7.centos
    update_cache: yes
    state: present

- name: Docker config path
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "/etc/docker"
    - "/etc/docker/certs"
  tags: config

- name: Config file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0600
  tags: config

- name: install tls
  debug:
    msg: "hhhhhhhhhhhh"
  when: DOCKER_TLS
  tags: config

- name: Add in service
  service: name=docker enabled=yes

- name: Restart docker
  service: name=docker state=restarted
  tags: config

- name: install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ COMPOSE_VERSION }}/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    group: root
    owner: root
    mode: 0755
  tags: compose


- name: include swarm
  include: swarm.yml
  tags: swarm